"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { 
  Search, 
  Download, 
  Calendar, 
  User, 
  Layers, 
  Eye, 
  Trash2,
  SlidersHorizontal,
  X
} from "lucide-react";
import { db, DbEstimate } from "@/lib/db";

// Standard formatting for currency
const formatCurrency = (val: number) => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  }).format(val);
};

export default function HistoryPage() {
  const [estimates, setEstimates] = useState<DbEstimate[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [selectedWood, setSelectedWood] = useState("All");

  // Load estimates on mount
  useEffect(() => {
    const fetchEstimates = async () => {
      try {
        const data = await db.getEstimates();
        setEstimates(data);
      } catch (err) {
        console.error("Failed to fetch estimates:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchEstimates();
  }, []);

  // Filter logic
  const filtered = estimates.filter(est => {
    const searchLower = search.toLowerCase();
    const matchesSearch = 
      est.category.toLowerCase().includes(searchLower) ||
      est.wood_type.toLowerCase().includes(searchLower) ||
      est.user_id.toLowerCase().includes(searchLower);

    const matchesCategory = selectedCategory === "All" || est.category === selectedCategory;
    const matchesWood = selectedWood === "All" || est.wood_type === selectedWood;

    return matchesSearch && matchesCategory && matchesWood;
  });

  // Extract unique categories and woods for filter dropdowns
  const categories = ["All", ...Array.from(new Set(estimates.map(e => e.category)))];
  const woodTypes = ["All", ...Array.from(new Set(estimates.map(e => e.wood_type)))];

  // CSV Export logic
  const handleExportCSV = () => {
    if (filtered.length === 0) return;

    // Define headers
    const headers = [
      "Estimate ID",
      "Date Generated",
      "User Email",
      "Category",
      "Wood Type",
      "Dimensions (LxWxH)",
      "Special Features",
      "Design Complexity",
      "Min Price (INR)",
      "Recommended Price (INR)",
      "Max Price (INR)",
      "Confidence Score (%)"
    ];

    // Map rows
    const rows = filtered.map(est => [
      est.id,
      new Date(est.created_at).toLocaleDateString(),
      est.user_id,
      est.category,
      est.wood_type,
      `"${est.dimensions.length}x${est.dimensions.width}x${est.dimensions.height} cm"`,
      `"${est.features.join(", ")}"`,
      est.complexity,
      est.estimated_price.min,
      est.estimated_price.recommended,
      est.estimated_price.max,
      est.confidence_score
    ]);

    // Build CSV content
    const csvContent = 
      "data:text/csv;charset=utf-8," + 
      [headers.join(","), ...rows.map(r => r.join(","))].join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `ZOOSH_Estimate_History_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const clearFilters = () => {
    setSearch("");
    setSelectedCategory("All");
    setSelectedWood("All");
  };

  return (
    <div className="space-y-8">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-neutral-800 pb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-wider uppercase">Estimation History</h1>
          <p className="text-sm text-neutral-400 mt-1">Review, filter, and audit past price estimates generated by the sales team.</p>
        </div>
        <button
          onClick={handleExportCSV}
          disabled={filtered.length === 0}
          className="flex items-center gap-2 px-5 py-2.5 rounded-md text-sm font-semibold bg-white text-black hover:bg-neutral-200 transition-colors disabled:opacity-50"
        >
          <Download className="w-4 h-4" />
          Export CSV
        </button>
      </div>

      {/* Filter / Search Bar */}
      <div className="bg-neutral-900 border border-neutral-800 rounded-lg p-5">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
          
          {/* Search Input */}
          <div className="md:col-span-2 space-y-2">
            <label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Search</label>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4.5 h-4.5 text-neutral-600" />
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search category, wood type, or user email..."
                className="w-full bg-neutral-950 border border-neutral-800 rounded-md py-2.5 pl-10 pr-4 text-sm text-white placeholder-neutral-700 focus:outline-none focus:border-neutral-500 transition-colors"
              />
            </div>
          </div>

          {/* Category Filter */}
          <div className="space-y-2">
            <label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Category</label>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="w-full bg-neutral-950 border border-neutral-800 rounded-md py-2.5 px-3 text-sm text-white focus:outline-none focus:border-neutral-500"
            >
              {categories.map(c => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>

          {/* Wood Filter */}
          <div className="space-y-2">
            <label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Wood Material</label>
            <select
              value={selectedWood}
              onChange={(e) => setSelectedWood(e.target.value)}
              className="w-full bg-neutral-950 border border-neutral-800 rounded-md py-2.5 px-3 text-sm text-white focus:outline-none focus:border-neutral-500"
            >
              {woodTypes.map(w => (
                <option key={w} value={w}>{w}</option>
              ))}
            </select>
          </div>

        </div>

        {/* Clear Filters indicator */}
        {(search || selectedCategory !== "All" || selectedWood !== "All") && (
          <div className="mt-4 pt-4 border-t border-neutral-800 flex items-center justify-between">
            <div className="text-xs text-neutral-400">
              Showing {filtered.length} of {estimates.length} results matching filter criteria.
            </div>
            <button 
              onClick={clearFilters}
              className="text-xs text-white hover:underline flex items-center gap-1 font-semibold"
            >
              <X className="w-3.5 h-3.5" />
              Clear Filters
            </button>
          </div>
        )}
      </div>

      {/* History Log Table */}
      <div className="bg-neutral-900 border border-neutral-800 rounded-lg overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-neutral-500 flex flex-col items-center justify-center gap-3">
            <div className="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin" />
            <p className="text-sm">Loading estimation history logs...</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="p-12 text-center text-neutral-500">
            <SlidersHorizontal className="w-10 h-10 stroke-[1] mx-auto text-neutral-600 mb-3" />
            <p className="text-sm">No estimation logs found matching filters.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="bg-neutral-950 text-neutral-400 border-b border-neutral-800 uppercase tracking-widest text-[9px] font-bold">
                  <th className="py-4 px-6">Image</th>
                  <th className="py-4 px-6">Date</th>
                  <th className="py-4 px-6">Category</th>
                  <th className="py-4 px-6">Specs</th>
                  <th className="py-4 px-6">Sales Rep</th>
                  <th className="py-4 px-6 text-right">Recommended Price</th>
                  <th className="py-4 px-6 text-center">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-800">
                {filtered.map((est) => (
                  <tr key={est.id} className="hover:bg-neutral-800/20 transition-colors">
                    <td className="py-4 px-6">
                      <div className="w-10 h-10 bg-neutral-950 border border-neutral-800 rounded overflow-hidden relative flex items-center justify-center">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img 
                          src={est.image_url} 
                          alt={est.category} 
                          className="object-cover w-full h-full"
                        />
                      </div>
                    </td>
                    <td className="py-4 px-6 text-neutral-300">
                      {new Date(est.created_at).toLocaleDateString(undefined, {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric'
                      })}
                    </td>
                    <td className="py-4 px-6 font-bold text-white">
                      {est.category}
                    </td>
                    <td className="py-4 px-6 text-neutral-400 space-y-0.5">
                      <div>Wood: <span className="text-white font-medium">{est.wood_type}</span></div>
                      <div>Dims: <span className="text-white font-medium">{est.dimensions.length}x{est.dimensions.width}x{est.dimensions.height} cm</span></div>
                    </td>
                    <td className="py-4 px-6 text-neutral-400">
                      <div className="flex items-center gap-1.5" title={est.user_id}>
                        <User className="w-3.5 h-3.5 text-neutral-500" />
                        <span className="truncate max-w-[120px]">{est.user_id}</span>
                      </div>
                    </td>
                    <td className="py-4 px-6 text-right font-bold text-white text-sm">
                      {formatCurrency(est.estimated_price.recommended)}
                      <div className="text-[10px] text-neutral-500 font-normal mt-0.5">
                        Range: {formatCurrency(est.estimated_price.min)} - {formatCurrency(est.estimated_price.max)}
                      </div>
                    </td>
                    <td className="py-4 px-6 text-center">
                      <Link
                        href={`/estimator/result/${est.id}`}
                        className="inline-flex items-center justify-center p-2 rounded-md border border-neutral-800 hover:bg-neutral-800 text-neutral-400 hover:text-white transition-colors"
                        title="View Estimation Breakdown"
                      >
                        <Eye className="w-4 h-4" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
