"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { 
  TrendingUp, 
  Package, 
  Layers, 
  ArrowRight, 
  Calculator,
  Calendar,
  FileText
} from "lucide-react";
import { db, DbProduct, DbEstimate } from "@/lib/db";

// Standard formatting for currency
const formatCurrency = (val: number) => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  }).format(val);
};

export default function DashboardPage() {
  const [products, setProducts] = useState<DbProduct[]>([]);
  const [estimates, setEstimates] = useState<DbEstimate[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadDashboardData = async () => {
      try {
        const prods = await db.getProducts();
        const ests = await db.getEstimates();
        setProducts(prods);
        setEstimates(ests);
      } catch (err) {
        console.error("Failed to load dashboard data:", err);
      } finally {
        setLoading(false);
      }
    };
    loadDashboardData();
  }, []);

  if (loading) {
    return (
      <div className="p-12 text-center text-neutral-500 flex flex-col items-center justify-center gap-3 min-h-[400px]">
        <div className="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin" />
        <p className="text-sm">Loading workspace dashboard metrics...</p>
      </div>
    );
  }

  // 1. Calculate Metrics
  const totalProducts = products.length;
  const totalEstimates = estimates.length;
  
  const avgEstimatedValue = totalEstimates > 0
    ? estimates.reduce((sum, est) => sum + est.estimated_price.recommended, 0) / totalEstimates
    : 0;

  // Calculate category stats
  const categoryCounts: Record<string, number> = {};
  estimates.forEach((est) => {
    categoryCounts[est.category] = (categoryCounts[est.category] || 0) + 1;
  });

  const sortedCategories = Object.entries(categoryCounts)
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count);

  const mostEstimatedCategory = sortedCategories[0]?.category || "None Yet";

  // Recent estimates (top 5)
  const recentEstimates = estimates.slice(0, 5);

  return (
    <div className="space-y-10">
      {/* Welcome Hero banner */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-neutral-800 pb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Sales Dashboard</h1>
          <p className="text-sm text-neutral-400 mt-1">ZOOSH Furnitures internal price estimation and catalog reference workspace.</p>
        </div>
        <Link 
          href="/new" 
          className="flex items-center gap-2 px-5 py-2.5 rounded-md text-sm font-semibold bg-white text-black hover:bg-neutral-200 transition-colors"
        >
          <Calculator className="w-4 h-4" />
          Create New Estimate
        </Link>
      </div>

      {/* Stats Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="p-6 bg-neutral-900 border border-neutral-800 rounded-lg flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Total Products</span>
            <Package className="w-5 h-5 text-neutral-400 stroke-[1.5]" />
          </div>
          <div className="mt-4">
            <h3 className="text-3xl font-bold">{totalProducts}</h3>
            <p className="text-xs text-neutral-500 mt-1">Reference catalog database</p>
          </div>
        </div>

        <div className="p-6 bg-neutral-900 border border-neutral-800 rounded-lg flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Total Estimates</span>
            <Calculator className="w-5 h-5 text-neutral-400 stroke-[1.5]" />
          </div>
          <div className="mt-4">
            <h3 className="text-3xl font-bold">{totalEstimates}</h3>
            <p className="text-xs text-neutral-500 mt-1">Generated by sales team</p>
          </div>
        </div>

        <div className="p-6 bg-neutral-900 border border-neutral-800 rounded-lg flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Avg Estimate Value</span>
            <TrendingUp className="w-5 h-5 text-neutral-400 stroke-[1.5]" />
          </div>
          <div className="mt-4">
            <h3 className="text-3xl font-bold">{formatCurrency(avgEstimatedValue)}</h3>
            <p className="text-xs text-neutral-500 mt-1">Recommended pricing value</p>
          </div>
        </div>

        <div className="p-6 bg-neutral-900 border border-neutral-800 rounded-lg flex flex-col justify-between">
          <div className="flex items-center justify-between text-neutral-400">
            <span className="text-xs font-semibold uppercase tracking-wider">Top Category</span>
            <Layers className="w-5 h-5 text-neutral-400 stroke-[1.5]" />
          </div>
          <div className="mt-4">
            <h3 className="text-xl font-bold truncate">{mostEstimatedCategory}</h3>
            <p className="text-xs text-neutral-500 mt-1">
              {sortedCategories[0] ? `${sortedCategories[0].count} estimates generated` : "No estimates recorded"}
            </p>
          </div>
        </div>
      </div>

      {/* Main Sections: Recent Estimates & Category Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Recent Estimates Column */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex justify-between items-center">
            <h2 className="text-lg font-bold tracking-wider uppercase">Recent Estimates</h2>
            <Link href="/history" className="text-xs font-semibold text-neutral-400 hover:text-white flex items-center gap-1">
              View History
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>

          <div className="bg-neutral-900 border border-neutral-800 rounded-lg overflow-hidden">
            {recentEstimates.length === 0 ? (
              <div className="p-8 text-center text-neutral-500">
                <Calculator className="w-12 h-12 stroke-[1] mx-auto text-neutral-600 mb-3" />
                <p className="text-sm">No price estimates generated yet.</p>
                <Link href="/new" className="text-xs text-white hover:underline mt-2 inline-block font-semibold">
                  Generate your first estimate now
                </Link>
              </div>
            ) : (
              <div className="divide-y divide-neutral-800">
                {recentEstimates.map((est) => (
                  <Link 
                    key={est.id} 
                    href={`/result/${est.id}`}
                    className="block p-4 hover:bg-neutral-800/40 transition-colors"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-neutral-950 border border-neutral-800 rounded-md overflow-hidden relative flex-shrink-0 flex items-center justify-center">
                          {/* eslint-disable-next-line @next/next/no-img-element */}
                          <img 
                            src={est.image_url} 
                            alt={est.category} 
                            className="object-cover w-full h-full" 
                          />
                        </div>
                        <div>
                          <h4 className="font-semibold text-sm">{est.category}</h4>
                          <div className="flex items-center gap-2 text-xs text-neutral-500 mt-1">
                            <span className="font-light">{est.wood_type}</span>
                            <span>•</span>
                            <span>{est.dimensions.length}x{est.dimensions.width}x{est.dimensions.height} cm</span>
                          </div>
                        </div>
                      </div>

                      <div className="text-right">
                        <span className="text-sm font-bold text-white">
                          {formatCurrency(est.estimated_price.recommended)}
                        </span>
                        <div className="flex items-center gap-1.5 justify-end text-[10px] text-neutral-400 mt-1">
                          <span className="px-1.5 py-0.5 rounded-full bg-neutral-800 text-[10px]">
                            {est.complexity}
                          </span>
                          <span>•</span>
                          <span className="text-neutral-500">
                            {est.confidence_score}% Match
                          </span>
                        </div>
                      </div>
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Categories Stats Column */}
        <div className="space-y-4">
          <h2 className="text-lg font-bold tracking-wider uppercase">Category Metrics</h2>
          <div className="bg-neutral-900 border border-neutral-800 rounded-lg p-6 space-y-6">
            <h3 className="text-sm font-semibold text-neutral-400">Estimation Distribution</h3>
            
            {sortedCategories.length === 0 ? (
              <p className="text-xs text-neutral-500 text-center py-6">No records to distribute</p>
            ) : (
              <div className="space-y-4">
                {sortedCategories.map(({ category, count }) => {
                  const percentage = totalEstimates > 0 ? (count / totalEstimates) * 100 : 0;
                  return (
                    <div key={category} className="space-y-1.5">
                      <div className="flex justify-between items-center text-xs">
                        <span className="font-medium text-neutral-300">{category}</span>
                        <span className="text-neutral-500 font-semibold">{count} estimates</span>
                      </div>
                      <div className="w-full bg-neutral-950 h-2 rounded-full overflow-hidden border border-neutral-900">
                        <div 
                          className="bg-white h-full rounded-full" 
                          style={{ width: `${percentage}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            <div className="border-t border-neutral-800 pt-4 flex flex-col gap-2.5">
              <Link 
                href="/history"
                className="flex items-center justify-between text-xs text-neutral-400 hover:text-white transition-colors"
              >
                <span className="flex items-center gap-2">
                  <Calendar className="w-3.5 h-3.5" />
                  Full History Log
                </span>
                <ArrowRight className="w-3 h-3" />
              </Link>
              <Link 
                href="/admin"
                className="flex items-center justify-between text-xs text-neutral-400 hover:text-white transition-colors"
              >
                <span className="flex items-center gap-2">
                  <FileText className="w-3.5 h-3.5" />
                  Manage Catalogs
                </span>
                <ArrowRight className="w-3 h-3" />
              </Link>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
